name: Upload XMP Metadata
on:
  workflow_dispatch  # Triggered manually

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_PAT }}  # Use the token for authentication

      - name: Upload XMP Metadata
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"

          echo "# Placeholder for XMP Metadata File" > XMP_Metadata_Scans.md
          git add XMP_Metadata_Scans.md
          git commit -m "Add XMP Metadata summary"
          git push
